### ISSUE TITLE
Still need to change delta_pixel_detector in recon function

### ISSUE THREAD

**Issue by bommaritom** [cabouman/mbircone#104]
Hi Diyu,

I have created the branch `quick_signature_changes` to update several function signatures in preparation for a laminography wrapper. 

In `recon`, I have changed the argument `delta_pixel_detector` to two arguments, `delta_det_channel` and `delta_det_row`. But `recon` is not completely updated; there still exist references to `delta_pixel_detector` in:

- The function call to `auto_sigma_y` on line 464 
- The function call to `auto_sigma_x` on line 470
- The function call to `sigma_p` on line 540

This is because these three functions accept a variable named `delta_pixel_detector`, which we had previously set to the value for `delta_pixel_detector` received by `recon`; however, this argument no longer exists in `recon`.

There are several ways to resolve this. For instance, to resolve the calls to `create_sino_params_dict` on lines 445 and 599, I modified the function `create_sino_params_dict` so that it also used the decoupled `delta_det_channel` and `delta_det_row`, instead of `delta_pixel_detector`. An alternative solution would be to make some computation with `delta_det_channel` and `delta_det_row` within `recon`, so that we end up passing a single variable in the function call. The important thing is that `recon` run with the decoupled variables.

I'm tagging you on this because I'm not sure the best way to resolve this.

**Comment by dyang37** [comment]
Hi Marco,
I'm looping Dr. Bouman @cabouman into this discussion also, since Dr. Bouman designed the auto_sigma functions himself.

In auto_sigma_y, "delta_pixel_detector" is used to simply calculate the default pixel pitch value.
Therefore, given the new implementation of the default image pixel pitch in line 437:
```
delta_pixel_image = np.min(delta_det_channel, delta_det_row) /magnification
```
I would say we do the same for auto_sigma_y. Specifically, we replace `delta_pixel_detector` with `delta_det_row` and `delta_det_channel` in the function signature, and change line 134 to the following:
```
default_pixel_pitch = np.min(delta_det_channel, delta_det_row) /magnification
```


In `auto_sigma_prior` (and hence `auto_sigma_x` and `auto_sigma_p`), `delta_pixel_detector` is used to calculate the path length of a typical projection, given as `(num_det_channels * delta_pixel_detector / magnification)` at line 172.

Therefore, I would suggest to directly replace `delta_pixel_detector` with `delta_det_channel` in those three functions.

**Comment by cabouman** [comment]
Marco, good job raising this flag!!
Here is what I suggest. Make the best changes you and Diyu can come up with.
Then we will go over the changes together on Thursday.

**Comment by cabouman** [comment]
I think this has been completed.
