### ISSUE TITLE
auto_sigma_prior needs to depend on magnification

### ISSUE THREAD

**Issue by cabouman** [cabouman/mbircone#68]
The current versions of `auto_sigma_prior()`, `auto_sigma_x()`, and `auto_sigma_p()` were directly ported from SVMBIR, so they do not depend on `magnification`. I think this means that the value of the estimated values of `sigma_x` and `sigma_p` will be wrong for large values of `magnification`. However, we will want to double check this first by running some examples.

We will probably need to replace line 183 with:
`
typical_img_value = np.average(sino, weights=sino_indicator) / (num_det_channels * delta_pixel_detector/magnification)
`

Once this is tested, we will want to port these routines to SVMBIR since with the `fan` geometry SVMBIR also has `magnification`.

**Comment by dyang37** [comment]
Will work on this.
________________________________
From: Charles A Bouman ***@***.***>
Sent: Wednesday, May 11, 2022 10:00 AM
To: cabouman/mbircone ***@***.***>
Cc: Diyu Yang ***@***.***>; Assign ***@***.***>
Subject: [cabouman/mbircone] auto_sigma_prior needs to depend on magnification (Issue #68)


The current versions of auto_sigma_prior(), auto_sigma_x(), and auto_sigma_p() were directly ported from SVMBIR, so they do not depend on magnification. I think this means that the value of the estimated values of sigma_x and sigma_p will be wrong for large values of magnification. However, we will want to double check this first by running some examples.

We will probably need to replace line 183 with:
typical_img_value = np.average(sino, weights=sino_indicator) / (num_det_channels * delta_pixel_detector/magnification)

Once this is tested, we will want to port these routines to SVMBIR since with the fan geometry SVMBIR also has magnification.

**Comment by cabouman** [comment]
Something seems very wrong here. The entire idea is that this modification should make the regularization invariant to magnification.

Let's do the following experiment: Run the same data set (say the 3D shep logan phantom) using different values of magnification. Your reconstructions should look exactly the same, except that the value of the reconstruction should scale with the value of `magnification`. If this is not the case, then something is very wrong.

**Comment by dyang37** [comment]
> Something seems very wrong here. The entire idea is that this modification should make the regularization invariant to magnification.
> 
> Let's do the following experiment: Run the same data set (say the 3D shep logan phantom) using different values of magnification. Your reconstructions should look exactly the same, except that the value of the reconstruction should scale with the value of `magnification`. If this is not the case, then something is very wrong.

For the experiment you mentioned above, when setting different `magnification` values, should we preserve the value of `delta_pixel_image` (i.e. scale `delta_pixel_detector` according to `magnification` value s.t. `delta_pixel_image = delta_pixel_detector\magnification` stays constant)?

I agree with what you said. My point was that compared to the old value of `auto_sigma_prior` before changing the algorithm, the new value is about 5 times the old value when using the same `sharpness`, so we should adjust `sharpness` value in the demo to make sure it produces good images.

**Comment by cabouman** [comment]
OK, I think I know what the problem is. We have to include magnification in the `auto_sigma_y` function too due to a hack we have that accounts for resolution changes in multi-res reconstruction.

I think we need to change it from:
`
sigma_y = rel_noise_std * signal_rms * (delta_pixel_image / delta_pixel_detector) ** (0.5)
`
to this:

```
# compute the default_pixel_pitch = the detector pixel pitch in the image plane given the magnification
default_pixel_pitch = delta_pixel_detector / magnification

# compute the image pixel pitch relative to the default.
pixel_pitch_relative_to_default = delta_pixel_image / default_pixel_pitch

# compute sigma_y and scale by relative pixel pitch
sigma_y = rel_noise_std * signal_rms * (pixel_pitch_relative_to_default ** 0.5)
```

**Comment by cabouman** [comment]
This was fixed, and tested. It seems to work fine.
